### PR TITLE
WIP: Add RowMapper for reusing same in multiple sql plugin

### PR DESCRIPTION
**Pull request by chotuchaudhary**
I have remove `RowMapper.java` from `mysql-plugin` and add it here. So that it can be reused in `postgresql` and `mysql` plugins

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
Thanks @chotuchaudhary. This is better, but I think we should slightly restructure the RowMapper to be specific to SQL dbs and be specific to each recipe.

Right now, we have two recipes (a recipe is a self contained module. One can use one recipe without using the other):
- Session
- EmailPassword
The interfaces and classes for these are separated into two separate packages (`plugininterface.emailpassword` and `plugininterface.session`. So we also need to create two `RowMapper` classes - one inside each of the packages, which deals only with the objects pertaining to that recipe. So for example, the `RowMapper` inside the session recipe will contain `SessionInfoMapper` and not `PasswordResetTokenInfoMapper`. Likewise, the `RowMapper` inside the emailpassword recipe will not contain `SessionInfoMapper`, but will contain `PasswordResetTokenInfoMapper`. 

As a result, the `SessionQueries` file in the plugin should only have to import the `RowMapper` from `plugininterface.session`, and the `EmailPasswordQueries` should only have to import the `RowMapper` from `plugininterface.emailpassword`. There should also be a RowMapper for `GeneralQueries` which makes the SQL result to objects like `KeyValueInfo`.

The other "dimension" is the type of the database. There are two types:
- SQL
- NoSQL

This is reflected by having two packages within each recipe. For example, we have `plugininterface.session.sqlStorage` and `plugininterface.session.nosqlStorage`. We don't have this for emailpassword yet since we don't support NoSQL dbs for that recipe (yet). This, in turn implies that the `RowMapper` must be inside the `*.sqlStorage` package, since they apply only to SQL dbs.

Finally, I have an argument for not doing this change at all (what do you think of this?): By adding `RowMapper` into the interface layer, we are no longer encapsulating the details of the queries to the plugin. For example, by doing this, we are enforcing that all SQL plugins must have the exact same column names and types. Is this the best idea?

**Comment by rishabhpoddar** [comment]
@chotuchaudhary will you do the above refactor?

**Comment by chotuchaudhary** [comment]
@rishabhpoddar , Thanks for the detailed explanation. I am working on it. will update you soon.

**Comment by rishabhpoddar** [comment]
Thank you @chotuchaudhary

**Comment by chotuchaudhary** [comment]
> Finally, I have an argument for not doing this change at all (what do you think of this?)

Totally agreed! let's not do it.
>By adding RowMapper into the interface layer, we are no longer encapsulating the details of the queries to the plugin. For example, by doing this, we are enforcing that all SQL plugins must have the exact same column names and types. Is this the best idea?

We can create below `RowMapper` abstract class in `plugin-interface`.  By doing this, we are giving flexibility to `plugin` to provide any implementation. Plugins are free to have different column names and types.
```java
public abstract class RowMapper<P, Q> {
    public abstract P map(Q rs) throws Exception;
}
```


`RowMapper` can be extend in any `Sql/NoSql plugin`.
i.e below example is given for `Mysql plugin`

```java
    class UserInfoMapper extends RowMapper<UserInfo, ResultSet> {
        static final UserInfoMapper INSTANCE = new UserInfoMapper();

        public static UserInfoMapper getInstance(){
            return INSTANCE;
        }

        private UserInfoMapper(){
        }

        @Override
        public UserInfo map(ResultSet result) throws Exception{
            return new UserInfo(result.getString("user_id"), result.getString("email"),
                    result.getString("password_hash"),
                    result.getLong("time_joined"));
        }
    }
```
Similarly, if we want to extend it in `MongoDB plugin`
```java
    static class SessionInfoMapper extends RowMapper<UserInfo, Document> {
        static final SessionInfoMapper INSTANCE = new SessionInfoMapper();

        public static SessionInfoMapper getInstance(){
            return INSTANCE;
        }

        private SessionInfoMapper(){
        }

        @Override
        public SessionInfo map(Document result) throws Exception {
            return new SessionInfo(sessionHandle, result.getString("user_id"),
                result.getString("refresh_token_hash_2"),
                new JsonParser().parse(result.getString("session_data")).getAsJsonObject(),
                result.getLong("expires_at"),
                new JsonParser().parse(result.getString("jwt_user_payload")).getAsJsonObject(),
                result.getLong("created_at_time"));
        }
    }
```

we can use `RowMapper` in different ways.
```java
// One way
RowMapper<UserInfo, ResultSet> rowMapper = UserInfoMapper.getInstance();
rowMapper.map(rs);
// or 
 UserInfoMapper.getInstance().map(rs);
 ```
 Please let me know your thoughts on this.

**Comment by rishabhpoddar** [comment]
hey @chotuchaudhary this sounds like a good idea! Let's go for it! Apart from doing this for postgresql and mysql plugins, there is also a sqlite, in memory db in the core itself. The code structure of that is almost identical to that of the other plugins, so please feel free to use a mapper for that too. The package name for the in mem db is `io.supertokens.inmemorydb.*`.

**Comment by chotuchaudhary** [comment]
@rishabhpoddar I have make the changes according to above comments in `plugin-interface` and `postgresql-plugin`.
Here is the PR for [postgresql-plugin](https://github.com/supertokens/supertokens-postgresql-plugin/pull/7)

**Comment by rishabhpoddar** [comment]
@chotuchaudhary the changes seem good! thanks!! If you are doing the changes for mysql & sqlite as well, please let me know. After they are done, I'll merge all the PRs. 

If you are not doing them, then someone else can pick them up and after that, I'll merge the PRs.

Thanks once again :)

**Comment by chotuchaudhary** [comment]
@rishabhpoddar I have made above changes for `mysql` and `sqlite` as well. Please find PRs below.
MySql RowMapper : https://github.com/supertokens/supertokens-mysql-plugin/pull/7
Sqlite RowMapper : https://github.com/supertokens/supertokens-core/pull/136
PostgresSql RowMapper : https://github.com/supertokens/supertokens-postgresql-plugin/pull/7

**Comment by rishabhpoddar** [comment]
@chotuchaudhary thanks for your contribution. I have merged all the PRs. Will release these in the next version!

**Comment by rishabhpoddar** [comment]
@chotuchaudhary i had to undo this merge since I merged it with master.. however, your changes are in branch `2.4`, which will get merged to master for the next release

**Comment by rishabhpoddar** [comment]
@chotuchaudhary if you like, you can also make the corresponding changes to the MongoDB plugin.

**Comment by chotuchaudhary** [comment]
Done the changes for [MongoDB plugin](https://github.com/supertokens/supertokens-mongodb-plugin) as well.
PR : https://github.com/supertokens/supertokens-mongodb-plugin/pull/6

**Pull request merged**
